- name: Rundeck | create linux users as we use PAM auth
  user:
    name: "{{ item.name }}"
    comment: "{{ system_users[item.name]['name'] }}"
    shell: /bin/bash
    groups: adm,dialout
    append: yes
    password: "{{ system_users[item.name]['password'] }}"
  with_items: "{{ rundeck_users }}"
  tags:
    - rundeck
    - users

- name: Rundeck | update basic security to have users
  lineinfile:
    dest: /etc/rundeck/realm.properties
    regexp: "^{{ item.name }}"
    line: "{{ item.name }}: -,{{ item.roles|join(',')}}"
    state: present
  when: rundeck_users|length > 0 
  with_items: "{{ rundeck_users }}"
  notify:
    - restart rundeck
  tags:
    - rundeck
    - users

- name: Rundeck | remove admin user
  lineinfile:
    backup: yes
    dest: /etc/rundeck/realm.properties
    regexp: "^admin:admin,user,admin,architect,deploy,build"
    state: absent
  when: rundeck_users|length > 0
  notify:
    - restart rundeck
  tags:
    - rundeck
    - users

- name: Rundeck | project specific acl policies
  template:
    src: etc/rundeck/project.aclpolicy.j2
    dest: /etc/rundeck/{{ item }}.aclpolicy
    owner: rundeck
    group: rundeck
    mode: 0640
  with_items: "{{ rundeck_users|sum(attribute='roles', start=[]) |list|unique| difference(rundeck_default_roles)  }}"
  tags:
    - rundeck
    - users
